In [ ]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/fake_or_real_news.csv')
df.head()

Unnamed: 0  ... label
0        8476  ...  FAKE
1       10294  ...  FAKE
2        3608  ...  REAL
3       10142  ...  FAKE
4         875  ...  REAL

[5 rows x 4 columns]

In [ ]:
df.isnull().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [ ]:
label={'FAKE':0,'REAL':1}

df.label=[label[i] for i in df.label]
print(df)

      Unnamed: 0  ... label
0           8476  ...     0
1          10294  ...     0
2           3608  ...     1
3          10142  ...     0
4            875  ...     1
...          ...  ...   ...
6330        4490  ...     1
6331        8062  ...     0
6332        8622  ...     0
6333        4021  ...     1
6334        4330  ...     1

[6335 rows x 4 columns]


In [ ]:
x=df.drop(['label'],axis=1)
y=df['label']

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
voc_size=7000

In [ ]:
messages=x.copy()

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
import nltk
nltk.download('stopwords')
  

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
corpus=[]

for i in range(len(messages)):
  print(i)

  set=re.sub('[^a-zA-Z]',' ',messages['title'][i])
  set=re.sub('#\w+','',messages['title'][i])
  set=set.lower()
  set=set.split()
  set=[w for w in set if not w in stopwords.words('english')]
  set=' '.join(set)
  corpus.append(set)

Streaming output truncated to the last 5000 lines.
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524

In [ ]:
corpus

['smell hillary’s fear',
 'watch exact moment paul ryan committed political suicide trump rally (video)',
 'kerry go paris gesture sympathy',
 "bernie supporters twitter erupt anger dnc: 'we tried warn you!'",
 'battle new york: primary matters',
 'tehran, usa',
 'girl horrified watches boyfriend left facetime',
 '‘britain’s schindler’ dies 106',
 "fact check: trump clinton 'commander-in-chief' forum",
 'iran reportedly makes new push uranium concessions nuclear talks',
 'three clintons iowa, glimpse fire eluded hillary clinton’s campaign',
 'donald trump’s shockingly weak delegate game somehow got even worse',
 'strong solar storm, tech risks today | s0 news oct.26.2016 [video]',
 '10 ways america preparing world war 3',
 'trump takes cruz, lightly',
 'women lead differently',
 'shocking! michele obama & hillary caught glamorizing date rape promoters',
 'hillary clinton huge trouble america noticed sick thing hidden picture... * liberty writers news',
 "what's iran bill obama like?",


In [ ]:
one_hot=[one_hot(words,voc_size)for words in corpus]
one_hot

[[3375, 886, 3254],
 [6016, 536, 1552, 3244, 3598, 3907, 6992, 3902, 4437, 4939, 5837],
 [2077, 98, 1261, 2317, 6020],
 [5133, 391, 1626, 4871, 218, 1178, 709, 6181, 5384, 1768, 97],
 [1105, 2110, 6502, 2137, 6453],
 [2584, 3416],
 [1995, 4233, 3080, 2662, 4248, 1165],
 [296, 874, 6918, 1809],
 [6512, 3602, 4437, 733, 6406, 896, 1828, 2014],
 [650, 6183, 4833, 2110, 6044, 1172, 5664, 54, 3514],
 [5257, 5105, 2073, 3164, 4228, 2071, 3492, 1058, 6488],
 [1394, 5537, 3248, 6885, 639, 130, 5469, 3410, 1583, 1],
 [4980, 5826, 2944, 1874, 5744, 4814, 852, 5277, 1672, 1699, 1364, 5837],
 [4093, 6258, 4330, 4438, 6813, 38, 236],
 [4437, 5089, 5249, 1775],
 [4702, 4762, 177],
 [2565, 3193, 2847, 3492, 1720, 2390, 4649, 3109, 4404],
 [3492, 733, 1308, 2432, 4330, 2587, 652, 5695, 1671, 4165, 6022, 4213, 5277],
 [5293, 650, 4262, 2847, 5561],
 [4973, 397, 4053, 6091, 1236, 1630, 6776, 4330],
 [5996, 6071, 5537, 452, 1682, 4055],
 [2930, 5215, 3815, 4891, 4488, 4913, 4412, 3810, 1764, 2132],
 [349

In [ ]:
sent_len=20

embeddings=pad_sequences(one_hot,padding='post',maxlen=sent_len)
print(embeddings)

[[3375  886 3254 ...    0    0    0]
 [6016  536 1552 ...    0    0    0]
 [2077   98 1261 ...    0    0    0]
 ...
 [ 832 4437  903 ...    0    0    0]
 [ 375 2847 1926 ...    0    0    0]
 [2769  714 6749 ...    0    0    0]]


In [ ]:
len(embeddings)

6335

In [ ]:
embeddings[0]

array([3375,  886, 3254,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
embedding_vector=40

from tensorflow.keras.models import Sequential

model=Sequential([
                  Embedding(voc_size,embedding_vector,input_length=sent_len),
                  LSTM(100),
                  tf.keras.layers.Dense(1,activation='sigmoid')
])

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            280000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 336,501
Trainable params: 336,501
Non-trainable params: 0
_________________________________________________________________


In [ ]:
len(embeddings),y.shape

(6335, (6335,))

In [ ]:
import numpy as np
x_final=np.array(embeddings)
y_final=np.array(y)

In [ ]:
x_final.shape,y_final.shape

((6335, 20), (6335,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x_final,y_final,test_size=0.3,random_state=20)

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
70/70 [==============================] - 3s 44ms/step - loss: 0.0555 - accuracy: 0.9853 - val_loss: 1.0654 - val_accuracy: 0.7359
Epoch 2/10
70/70 [==============================] - 2s 36ms/step - loss: 0.0423 - accuracy: 0.9901 - val_loss: 0.9825 - val_accuracy: 0.7354
Epoch 3/10
70/70 [==============================] - 2s 35ms/step - loss: 0.0311 - accuracy: 0.9928 - val_loss: 1.1932 - val_accuracy: 0.7407
Epoch 4/10
70/70 [==============================] - 2s 35ms/step - loss: 0.0250 - accuracy: 0.9953 - val_loss: 1.2050 - val_accuracy: 0.7333
Epoch 5/10
70/70 [==============================] - 2s 35ms/step - loss: 0.0246 - accuracy: 0.9953 - val_loss: 1.3280 - val_accuracy: 0.7349
Epoch 6/10
70/70 [==============================] - 2s 35ms/step - loss: 0.0232 - accuracy: 0.9955 - val_loss: 1.3578 - val_accuracy: 0.7333
Epoch 7/10
70/70 [==============================] - 2s 35ms/step - loss: 0.0207 - accuracy: 0.9944 - val_loss: 1.5083 - val_accuracy: 0.7217
Epoch 8/10
70

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
embedding_vector=40

from tensorflow.keras.models import Sequential

model=Sequential([
                  Embedding(voc_size,embedding_vector,input_length=sent_len),
                  tf.keras.layers.Dropout(0.3),
                  LSTM(100),
                  tf.keras.layers.Dropout(0.3),
                  tf.keras.layers.Dense(1,activation='sigmoid')
])

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
70/70 [==============================] - 5s 43ms/step - loss: 0.6784 - accuracy: 0.5264 - val_loss: 0.5053 - val_accuracy: 0.7443
Epoch 2/10
70/70 [==============================] - 3s 36ms/step - loss: 0.3900 - accuracy: 0.8249 - val_loss: 0.4730 - val_accuracy: 0.7649
Epoch 3/10
70/70 [==============================] - 3s 36ms/step - loss: 0.2277 - accuracy: 0.9133 - val_loss: 0.5056 - val_accuracy: 0.7654
Epoch 4/10
70/70 [==============================] - 3s 36ms/step - loss: 0.1394 - accuracy: 0.9563 - val_loss: 0.5588 - val_accuracy: 0.7617
Epoch 5/10
70/70 [==============================] - 3s 37ms/step - loss: 0.1048 - accuracy: 0.9701 - val_loss: 0.6952 - val_accuracy: 0.7517
Epoch 6/10
70/70 [==============================] - 3s 36ms/step - loss: 0.0681 - accuracy: 0.9803 - val_loss: 0.9003 - val_accuracy: 0.7438
Epoch 7/10
70/70 [==============================] - 3s 36ms/step - loss: 0.0642 - accuracy: 0.9827 - val_loss: 0.8561 - val_accuracy: 0.7438
Epoch 8/10
70